// Generated by gencpp from file just_drone/tv_dim.msg
// DO NOT EDIT!


#ifndef JUST_DRONE_MESSAGE_TV_DIM_H
#define JUST_DRONE_MESSAGE_TV_DIM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace just_drone
{
template <class ContainerAllocator>
struct tv_dim_
{
  typedef tv_dim_<ContainerAllocator> Type;

  tv_dim_()
    : width(0)
    , height(0)  {
    }
  tv_dim_(const ContainerAllocator& _alloc)
    : width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::just_drone::tv_dim_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::just_drone::tv_dim_<ContainerAllocator> const> ConstPtr;

}; // struct tv_dim_

typedef ::just_drone::tv_dim_<std::allocator<void> > tv_dim;

typedef boost::shared_ptr< ::just_drone::tv_dim > tv_dimPtr;
typedef boost::shared_ptr< ::just_drone::tv_dim const> tv_dimConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::just_drone::tv_dim_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::just_drone::tv_dim_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::just_drone::tv_dim_<ContainerAllocator1> & lhs, const ::just_drone::tv_dim_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::just_drone::tv_dim_<ContainerAllocator1> & lhs, const ::just_drone::tv_dim_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace just_drone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::just_drone::tv_dim_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::just_drone::tv_dim_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::just_drone::tv_dim_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::just_drone::tv_dim_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::just_drone::tv_dim_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::just_drone::tv_dim_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::just_drone::tv_dim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4069c3fe743f7881e847e9b0ab5556a";
  }

  static const char* value(const ::just_drone::tv_dim_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4069c3fe743f788ULL;
  static const uint64_t static_value2 = 0x1e847e9b0ab5556aULL;
};

template<class ContainerAllocator>
struct DataType< ::just_drone::tv_dim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "just_drone/tv_dim";
  }

  static const char* value(const ::just_drone::tv_dim_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::just_drone::tv_dim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 width\n"
"int32 height\n"
;
  }

  static const char* value(const ::just_drone::tv_dim_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::just_drone::tv_dim_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tv_dim_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::just_drone::tv_dim_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::just_drone::tv_dim_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUST_DRONE_MESSAGE_TV_DIM_H
